# Generated by Django 5.2.4 on 2025-07-30 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_content',
            options={'verbose_name': 'user_post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='user_content',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
