# Generated by Django 5.2.4 on 2025-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_content_options_user_content_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_content',
            name='content_image',
            field=models.ImageField(blank=True, upload_to='user/content/images'),
        ),
    ]
