# Generated by Django 5.2.4 on 2025-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_content_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_content',
            name='content_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
